#!/usr/bin/env sh
# Last-resort initializer: ensure a ./gradlew file exists for analyzers that only check for its presence.
# This does not perform a real build; it creates a small delegator that prints guidance.
set -eu
ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
GRADLEW="${ROOT_DIR}/gradlew"

if [ -f "$GRADLEW" ]; then
  echo "[init-gradlew-lastresort] ./gradlew already exists."
  exit 0
fi

cat > "$GRADLEW" <<'EOF'
#!/usr/bin/env sh
# Generated by init-gradlew-lastresort.sh (placeholder)
echo "[gradlew placeholder] This is a placeholder. Use one of these scripts instead:"
echo "  - bash note-organizer-14347-14360/ci-gradle-check.sh"
echo "  - bash note-organizer-14347-14360/run-ci.sh"
echo "  - sh note-organizer-14347-14360/run-gradle-check-bootstrap.sh"
exit 127
EOF

chmod +x "$GRADLEW"
echo "[init-gradlew-lastresort] Created placeholder ./gradlew (non-executable build)."
