#!/usr/bin/env bash
# Lists all available Gradle/Bootstrap helper scripts in this repository with brief descriptions.

set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Gradle/Bootstrap helpers (run these from repository root):"
echo ""
printf "  %-40s %s\n" "ci-bootstrap-and-check.sh" "One-step: bootstrap wrapper via Expo Prebuild, then run 'gradle check'"
printf "  %-40s %s\n" "build-android.sh" "Bootstrap wrapper via prebuild, then run './gradlew assembleDebug'"
printf "  %-40s %s\n" "pre-gradle.sh" "Pre-gradle hook: fix exec bits and attempt bootstrap; runs check if possible"
printf "  %-40s %s\n" "preflight-ci.sh" "Preflight helper: fix exec bits and attempt bootstrap; prints wrapper status"
printf "  %-40s %s\n" "run-gradle.sh" "Bootstrap if needed, then forward any Gradle tasks to generated wrapper"
printf "  %-40s %s\n" "gradle-wrapper.sh" "CI-friendly wrapper substitute; forwards tasks after bootstrap"
printf "  %-40s %s\n" "gradlew-fallback.sh" "Fallback alias to run one-step bootstrap & check"
printf "  %-40s %s\n" "gradle-check.sh" "Bootstrap then run 'check' via generated wrapper"
printf "  %-40s %s\n" "gradlew-ci-task.sh" "Drop-in replacement for './gradlew <tasks>' in CI"
printf "  %-40s %s\n" "gradle-ci.sh" "Alias: call the one-step 'ci-bootstrap-and-check.sh'"
printf "  %-40s %s\n" "fix-exec-bits.sh" "Ensure all shim scripts are executable (when mounted without +x)"
printf "  %-40s %s\n" "before-gradle.sh" "Common CI hook: prepare and attempt 'check'"
printf "  %-40s %s\n" "init-gradle.sh" "Bootstrap (or build) and verify wrapper presence"
printf "  %-40s %s\n" "prepare-android-wrapper.sh" "Generate wrapper via prebuild if possible"
printf "  %-40s %s\n" "setup-and-bootstrap.sh" "Install app deps and then bootstrap wrapper"
echo ""
echo "Recommended one-step fix before any Gradle command:"
echo "  bash note-organizer-14347-14360/ci-bootstrap-and-check.sh"
echo ""
echo "Android app-level helpers (from notes_frontend/):"
printf "  %-40s %s\n" "scripts/bootstrap-android.sh" "Generate android wrapper via Expo Prebuild"
printf "  %-40s %s\n" "scripts/ci-build-android.sh" "Build after bootstrapping"
echo ""
echo "Note: The real Gradle wrapper is generated under notes_frontend/android by Expo Prebuild."
